import './globals.css'

export const metadata = {
  title: 'Task Board App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className='bg-cyan-900'>
          {children}
        </div>
      </body>
    </html>
  )
}
