import './globals.css'

export const metadata = {
  title: 'Task Board App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <div className='flex flex-col h-screen bg-cyan-900'>
      {children}
    </div>
  )
}
